name: SimpleLocalChat
version: '${version}'
main: com.github.tooooowa.simplelocalchat.SimpleLocalChat
api-version: '1.20'
authors: [towa]
description: This is a minecraft plugin to chat up close.
commands:
  range:
    description: チャット範囲を選択します
    usage: /<command>
    aliases: chatrange
    permission: simplelocalchat.commands.chatrange

permissions:
  simplelocalchat.commands.*:
    default: false
    description: SimpleLocalChatプラグインの各コマンドの権限
    children:
      simplelocalchat.commands.chatrange: true
  simplelocalchat.commands.chatrange:
    default: true
    description: チャット範囲を変更するコマンド